
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: /home/java_job
DB_NAME: java_job
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/java_job?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

File:
  uploadPath: ${BASE_LOCATION}\server\upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true
